### PR TITLE
Add configuration file as interface to code

### LINKED ISSUE #3: Add configuration file and call in code
Add a single configuration (.ini) file as a single file to declare paths to inputs and outputs.  Modify the code to extract values from this file.

### PR DESCRIPTION
**Pull request by crvernon**
A configuration file (`config.ini`) file was added as an interface to parameterize the existing code.  The following was also added/modified:

- scripts previously executed autonomously were wrapped in functions 
- a `Main.m` script and `Main()` function was added that takes only the path to the configuration file as an argument
- added missing functions from initial upload
- added `Setting-up and Executing the Code` section to the `README`
- changed the name of some functions to represent their role in the `Main.m` code
- added option to generate the entity-relationship output file without running the preprocessing code since the `.mat` preparatory files may already exist
- added option to generate plots

Resolves #3

### CODE REVIEW

**Comment by crvernon** [comment]
@cdburley Please add in the DOI path and download instructions in the `README` in the `Setting-up and Executing the Code` section for number 2, in place of the existing raw download information.

**Comment by crvernon** [comment]
@cdburley I decided to leave the output as a matlab structure file.  After looking around, there are plenty of 3rd party options for converting it into any user-desired format.  It may be good to explain the relationships and data within though in the `README`.

**Comment by cdburley** [comment]
> n

@crvernon I updated the readme to reflect the data DOIs for the EIA 861 and County_Metadata.xlsx input datasets.

**Comment by crvernon** [comment]
Looks good @cdburley .  Thanks!  Once you test the code to make sure it works and provides the expected output, could you go ahead and approve the PR, merge it into the master, and select the option to delete this branch?  This will compete your review - let me know if you have questions related to this process.

**Comment by cdburley** [comment]
Reviewed on 2-May on a Mac. Everything works as desired. Will approve PR and merge branches.

**Pull request merged**
